#!/usr/bin/env /root/miniconda3/bin/python
import argparse
import json
import subprocess

print("Searching...")


def evaluate_command(name, k, *,
                     algorithm="block_max_wand", index_type="block_simdbp",
                     wand_type="vbmw", stemmer="porter2"):
    return ("evaluate_queries "
            f"-t {index_type} "
            f"-a {algorithm} "
            f"-i {name}.{index_type} "
            f"-w {name}.{wand_type} "
            f"--stemmer {stemmer} "
            f"--documents {name}.fwd.doclex "
            f"--terms {name}.fwd.termlex "
            f"-k {k} "
            f"-q {name}.title "
            f"> /output/{name}-{k}")


def choose_evaluate_command(name, k):
    """For now, all execute the same way."""
    return evaluate_command(name, k)


parser = argparse.ArgumentParser()
parser.add_argument("--json", type=json.loads, required=True,
                    help="the json input")
args, _ = parser.parse_known_args()
name, k = args.json["collection"]["name"], args.json["top_k"]

subprocess.check_call(
    "extract_topics -i {0} -o {1}".format(args.json["topic"]["path"], name),
    shell=True
)
subprocess.check_call(
    choose_evaluate_command(name, k),
    shell=True
)
