#!/usr/bin/env python3

import argparse
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("--collection", required=True, type=str, help="the name of the collection")
parser.add_argument("--topic", required=True, type=str, help="the name of the topic file")
parser.add_argument("--topic_format", default="TREC", type=str, help="the format of the topic file")

args = parser.parse_args()

subprocess.run("/pisa/build/bin/queries -t block_simdbp -a block_max_wand -i {0}.block_simdbp -w {0}.vbmw -q {1} -k 10".format(args.collection, args.topic).split())
