#!/usr/bin/env python3
import argparse
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("--collection", required=True, type=str, help="the name of the collection")
parser.add_argument("--topic", required=True, type=str, help="the name of the topic file")
parser.add_argument("--topic_format", default="TREC", type=str, help="the format of the topic file")
parser.add_argument("--top_k", default=1000, type=int, help="the number of results for top-k retrieval")

args, _ = parser.parse_known_args()

subprocess.check_call("evaluate_queries -t block_simdbp -i Robust04.block_simdbp -w {0}.vbmw -q /input/collections/{1} --stemmer porter2 "
                      "--documents {0}.fwd.documents --terms {0}.fwd.terms -k {2} > /output/{0}-{2}"
               .format(args.collection, args.topic, args.top_k), shell=True)
